spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing_task
    password: test
    username: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8191

